/**
 * pdvAutoSync.ts
 * Sincronização automática da planilha de produtos PDV.
 * Chamado pelo endpoint POST /api/scheduled/sync-products (tarefa agendada Manus).
 * Reutiliza a mesma lógica do pdvSync.sync, sem exigir autenticação PDV.
 */
import mysql from "mysql2/promise";
import { savePdvNotification } from "./pdvNotifications";
import { autoSyncProductToSite } from "./pdvSiteSync";

const SHEET_ID = "1SGUr5Sh2gZ5nkYg0km-QhllQS4Jm2_aVxy6PuyATsLU";
const SHEET_RANGE = "PRODUTOS!A2:P2000";

// ── Mapa de abreviações (idêntico ao pdvSync.ts) ──────────────────────────────
const LINHA_MAP: Record<string, string> = { TAILANDESA: 'CA', NACIONAL: 'NA', TORCEDOR: 'TO', PECA: 'PE' };
const MODELO_MAP: Record<string, string> = { JOGADOR: 'JG', TORCEDOR: 'TO', TAILANDESA: 'CA', DRYFIT: 'DR', VENDEDOR: 'VE' };
const STOPWORDS = new Set(['COM','DE','DA','DO','NO','NA','E','A','O','EM','AO','AS','OS','UM','UMA']);
const DESC_OVERRIDE: Record<string, string> = {
  'FEMI-PRETA COM GOLA AMARELA RIO': 'FEMI-PRET-GOLA-AMAR',
  'FEMI-PRETA GOLA AMARELA RIO':     'FEMI-PRET-GOLA-RIO',
  'FEMI-VERDE GOLA AMARELA':         'FEMI-VERD-GOLA',
  'FEMI-VERDE GOLA AMARELA RIO':     'FEMI-VERD-GOLA-RIO',
  'VERMELHO COM LISTRA PRETA':       'VERM-LIST-PRET',
  'VERMELHA COM LISTRA PRETA NO OMBRO': 'VERM-LIST-OMBR',
};

function removeAcentos(s: string): string {
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}
function slugifyCode(s: string): string {
  if (!s) return '';
  let r = removeAcentos(s.trim().toUpperCase());
  r = r.replace(/[^A-Z0-9 \-]/g, '');
  r = r.replace(/\s+/g, '-');
  r = r.replace(/-+/g, '-');
  return r.replace(/^-|-$/g, '');
}
function abreviarCampo(s: string, mapa: Record<string, string>, n: number): string {
  if (!s) return '';
  const chave = s.trim().toUpperCase();
  if (mapa[chave]) return mapa[chave];
  return slugifyCode(chave).slice(0, n);
}
function palavrasSig(desc: string): string[] {
  const s = removeAcentos(desc.toUpperCase());
  const palavras = s.match(/[A-Z0-9]+/g) || [];
  const sig = palavras.filter(p => !STOPWORDS.has(p));
  return sig.length > 0 ? sig : palavras;
}
function abreviarDesc(desc: string, n = 2): string {
  if (!desc) return '';
  const chave = removeAcentos(desc.trim().toUpperCase());
  if (DESC_OVERRIDE[chave]) return DESC_OVERRIDE[chave];
  const sig = palavrasSig(desc);
  return sig.slice(0, n).map(p => p.slice(0, 4)).join('-');
}
function gerarCodigo(linha: string, modelo: string, time: string, desc: string, tamanho: string): string {
  const partes: string[] = [];
  const l = abreviarCampo(linha, LINHA_MAP, 2); if (l) partes.push(l);
  const m = abreviarCampo(modelo, MODELO_MAP, 2); if (m) partes.push(m);
  const t = abreviarCampo(time, {}, 3); if (t) partes.push(t);
  const d = abreviarDesc(desc, 2); if (d) partes.push(d);
  const tam = slugifyCode(tamanho); if (tam) partes.push(tam);
  return partes.join('-');
}

function parseMoney(raw: string): number {
  if (!raw) return 0;
  const clean = raw.toString().trim().replace(/[R$\s]/g, '').replace(',', '.');
  const n = parseFloat(clean);
  return isNaN(n) ? 0 : n;
}

interface SheetProduct {
  codigo: string;
  linha: string;
  modelo: string;
  time: string;
  descricao: string;
  tamanho: string;
  tipo: string;
  estoque: number;
  precoAtacado: number;
  precoVarejo: number;
  isActive: number;
  ptAtacado: number;
  ptVarejo: number;
  custo: number;
}

async function getDb() {
  const url = process.env.DATABASE_URL;
  if (!url) return null;
  return mysql.createConnection(url);
}

async function fetchAndParseSheet(apiKey: string): Promise<{ valid: SheetProduct[]; invalid: number; autoGenerated: number }> {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(SHEET_RANGE)}?key=${apiKey}`;
  const response = await fetch(url);
  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Google Sheets API error: ${response.status} — ${err}`);
  }
  const data = await response.json() as { values?: string[][] };
  const rows: string[][] = data.values || [];

  const rawProducts: SheetProduct[] = [];
  let invalid = 0;
  let autoGenerated = 0;

  for (const row of rows) {
    const time = (row[3] || '').trim();
    const tamanho = (row[5] || '').trim();
    const qtdRaw = (row[7] || '').trim();
    const atcRaw = (row[8] || '').trim();
    const varRaw = (row[9] || '').trim();

    if (!time || !tamanho) { invalid++; continue; }
    const qtd = parseInt(qtdRaw);
    if (isNaN(qtd) || qtd < 0) { invalid++; continue; }
    const atc = parseMoney(atcRaw);
    const varejo = parseMoney(varRaw);
    if (atc <= 0 || varejo <= 0) { invalid++; continue; }

    let codigo = (row[0] || '').trim();
    const linha = (row[1] || '').trim();
    const modelo = (row[2] || '').trim();
    const desc = (row[4] || '').trim();

    if (!codigo) {
      codigo = gerarCodigo(linha, modelo, time, desc, tamanho);
      if (!codigo) { invalid++; continue; }
      autoGenerated++;
    }

    const isActiveRaw = (row[11] || '').trim().toUpperCase();
    const isActive = isActiveRaw === '' || isActiveRaw === 'SIM' || isActiveRaw === '1' || isActiveRaw === 'TRUE' ? 1 : 0;

    rawProducts.push({
      codigo,
      linha,
      modelo,
      time,
      descricao: desc,
      tamanho,
      tipo: (row[6] || 'CAMISETA').trim(),
      estoque: qtd,
      precoAtacado: atc,
      precoVarejo: varejo,
      isActive,
      ptAtacado: parseMoney(row[14] || ''),
      ptVarejo: parseMoney(row[15] || ''),
      custo: parseMoney(row[10] || ''),
    });
  }

  // Deduplicar: manter o de maior estoque quando há duplicatas de código
  const deduped = new Map<string, SheetProduct>();
  for (const p of rawProducts) {
    const existing = deduped.get(p.codigo);
    if (!existing || p.estoque > existing.estoque) {
      deduped.set(p.codigo, { ...p, estoque: existing ? existing.estoque + p.estoque : p.estoque });
    }
  }

  return { valid: Array.from(deduped.values()), invalid, autoGenerated };
}

export async function runAutoSync(): Promise<{
  inseridos: number;
  atualizados: number;
  ignorados: number;
  erros: number;
  autoGenerated: number;
  tempoSegundos: number;
  timestamp: string;
}> {
  const apiKey = process.env.GOOGLE_SHEETS_API_KEY;
  if (!apiKey) throw new Error("GOOGLE_SHEETS_API_KEY não configurada");

  const startTime = Date.now();
  const { valid, invalid, autoGenerated } = await fetchAndParseSheet(apiKey);

  if (valid.length === 0) {
    return { inseridos: 0, atualizados: 0, ignorados: invalid, erros: 0, autoGenerated, tempoSegundos: 0, timestamp: new Date().toISOString() };
  }

  const db = await getDb();
  if (!db) throw new Error("Banco de dados indisponível");

  // Estado atual do banco
  const [existingRows] = await db.execute(
    "SELECT codigo, estoque, precoAtacado, precoVarejo, isActive FROM pdv_products WHERE codigo IS NOT NULL AND codigo != ''"
  );
  const existingMap = new Map<string, any>();
  for (const row of existingRows as any[]) {
    existingMap.set(row.codigo, row);
  }

  const novosProdutos: SheetProduct[] = [];
  let inseridos = 0;
  let atualizados = 0;
  let erros = 0;

  const CHUNK_SIZE = 100;
  for (let i = 0; i < valid.length; i += CHUNK_SIZE) {
    const chunk = valid.slice(i, i + CHUNK_SIZE);
    try {
      const placeholders = chunk.map(() => "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())").join(", ");
      const values: any[] = [];
      for (const p of chunk) {
        values.push(
          p.codigo, p.linha, p.modelo, p.time, p.descricao,
          p.tamanho, p.tipo, p.estoque, p.precoAtacado, p.precoVarejo, p.isActive,
          p.ptAtacado, p.ptVarejo, p.custo
        );
      }
      await db.execute(
        `INSERT INTO pdv_products
          (codigo, linha, modelo, \`time\`, descricao, tamanho, tipo, estoque, precoAtacado, precoVarejo, isActive, ptAtacado, ptVarejo, custo, createdAt, updatedAt)
         VALUES ${placeholders}
         ON DUPLICATE KEY UPDATE
           linha=VALUES(linha), modelo=VALUES(modelo), \`time\`=VALUES(\`time\`),
           descricao=VALUES(descricao), tamanho=VALUES(tamanho), tipo=VALUES(tipo),
           estoque=VALUES(estoque), precoAtacado=VALUES(precoAtacado),
           precoVarejo=VALUES(precoVarejo), isActive=VALUES(isActive),
           ptAtacado=VALUES(ptAtacado), ptVarejo=VALUES(ptVarejo),
           custo=VALUES(custo),
           updatedAt=NOW()`,
        values
      );
      for (const p of chunk) {
        if (existingMap.has(p.codigo)) atualizados++;
        else {
          inseridos++;
          novosProdutos.push(p);
        }
      }
    } catch (err) {
      erros += chunk.length;
      console.error(`[AutoSync] Erro no chunk ${i}-${i + CHUNK_SIZE}:`, err);
    }
  }

  await db.end();

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  const timestamp = new Date().toISOString();
  console.log(`[AutoSync] ${timestamp} — ${elapsed}s — Inseridos: ${inseridos}, Atualizados: ${atualizados}, Ignorados: ${invalid}, Erros: ${erros}, AutoGerados: ${autoGenerated}`);

  // Notificação se houver novos produtos
  if (novosProdutos.length > 0) {
    try {
      const lista = novosProdutos.slice(0, 10)
        .map(p => `• ${p.codigo} — ${p.time} ${p.descricao} (${p.tamanho}) | ATC: R$${p.precoAtacado} / VAR: R$${p.precoVarejo}`)
        .join("\n");
      const sufixo = novosProdutos.length > 10 ? `\n... e mais ${novosProdutos.length - 10} produto(s).` : "";
      await savePdvNotification(
        "novo_produto",
        `[AutoSync] ${novosProdutos.length} novo(s) produto(s) adicionado(s)`,
        `Sincronização automática\nData: ${new Date().toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })}\n\nNovos produtos:\n${lista}${sufixo}`
      );
    } catch (e) { console.error("[AutoSync] Erro notificação:", e); }

    // Auto-sync site
    const codigosBase = new Set<string>();
    for (const p of novosProdutos) {
      if (p.codigo) {
        const parts = p.codigo.split("-");
        const base = parts.length > 1 ? parts.slice(0, -1).join("-") : p.codigo;
        codigosBase.add(base);
      }
    }
    for (const base of Array.from(codigosBase)) {
      autoSyncProductToSite(base).catch(err =>
        console.error(`[AutoSync] Erro ao sync site para ${base}:`, err)
      );
    }
  }

  return { inseridos, atualizados, ignorados: invalid, erros, autoGenerated, tempoSegundos: parseFloat(elapsed), timestamp };
}
